[package]
name = "concoct"
version = "0.2.0-alpha.2"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Generic UI compiler and runtime library"
repository = "https://github.com/concoct-rs/concoct"

[workspace]
members = [
    ".",
    "macros",
]

[features]
full = []

[dependencies]
concoct-macros = "0.2.0-alpha.2"
dashmap = "5.4.0"
# concoct-macros = { path = "macros" }
lazy_static = "1.4.0"
