[package]
name = "concoct"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Generic UI compiler and runtime library"
repository = "https://github.com/concoct-rs/concoct"

[features]
full = []

[dependencies]
tokio = { version = "1.29.1", features = ["full"] }
accesskit = "0.11.1"
gl = "0.14.0"
glutin = "0.30.9"
glutin-winit = "0.3.0"
raw-window-handle = "0.5.2"
skia-safe = { version = "0.64.0", features = ["gl"] }
slotmap = "1.0.6"
taffy = "0.3.12"
winit = "0.28.6"
