[package]
name = "concoct"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
accesskit = "0.8.1"
slotmap = "1.0.6"
taffy = "0.2.2"
