[package]
name = "concoct"
version = "0.2.0-alpha.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Generic UI compiler and runtime library"
repository = "https://github.com/concoct-rs/concoct"

[workspace]
members = [
    ".",
    "macros",
]

[features]
full = []

[dependencies]
# concoct-macros = "0.2.0-alpha.1"
concoct-macros = { path = "macros" }
slotmap = "1.0.6"
tokio = { version = "1.29.1", features = ["full"] }
