[package]
name = "concoct"
version = "0.2.0"
edition = "2021"

[features]
full = []

[workspace]
members = [
    ".",
    "macros",
]

[dependencies]
clap = { version = "4.3.8", features = ["derive"] }
prettyplease = "0.2.9"
quote = "1.0.28"
syn = { version = "2.0.22", features = ["full", "fold", "visit"] }
