[package]
name = "concoct"
version = "0.5.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Generic UI compiler and runtime library"
repository = "https://github.com/concoct-rs/concoct"

[dependencies]
impl-trait-for-tuples = "0.2.2"
wasm-bindgen = "0.2.87"
web-sys = { version = "0.3.64", features = ["Event", "EventTarget", "Node", "Document", "HtmlCollection", "HtmlElement", "HtmlInputElement", "Window", "Text"] }
