[package]
name = "concoct"
version = "0.6.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Cross-platform UI framework"
repository = "https://github.com/concoct-rs/concoct"

[features]
web = ["dep:wasm-bindgen", "dep:web-sys"]

[dependencies]
impl-trait-for-tuples = "0.2.2"
wasm-bindgen = { version = "0.2.87", optional = true }

[dependencies.web-sys]
version = "0.3.64"
optional = true
features = [
    "Event",
    "EventTarget",
    "KeyboardEvent",
    "Node",
    "Document",
    "HtmlCollection",
    "HtmlElement",
    "HtmlInputElement",
    "Window",
    "Text"
]

[package.metadata.docs.rs]
all-features = true
