[package]
name = "concoct"
version = "0.2.0"
edition = "2021"

[workspace]
members = [
    ".",
    "macros"
]

[features]
full = []

[dependencies]
concoct-macros = { path = "macros" }
clap = { version = "4.3.8", features = ["derive"] }
log = "0.4.19"
prettyplease = "0.2.9"
quote = "1.0.28"
syn = { version = "2.0.22", features = ["full", "fold", "visit"] }

[package.metadata.rust-analyzer]
rustc_private = true
